name: crd
apiVersion: v1
version: 2.3.0
appVersion: 5.0.3
description: Helm chart for NeuVector's CRD services
home: https://neuvector.com
icon: https://avatars2.githubusercontent.com/u/19367275?s=200&v=4
maintainers:
  - name: becitsthere
    email: support@neuvector.com
engine: gotpl
