{{- if and .Values.manager.enabled .Values.manager.ingress.enabled .Values.manager.ingress.traefikIngressRoute -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: neuvector-webui-ingress
  namespace: {{ .Release.Namespace }}
{{- with .Values.manager.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.manager.ingress.host }}`) && PathPrefix(`{{ .Values.cve.adapter.ingress.path }}`)
    kind: Rule
    services:
      - name: neuvector-service-webui
        passHostHeader: true
        port: 8443
        scheme: https
{{- if .Values.manager.ingress.tls }}
  tls:
{{- if .Values.manager.ingress.secretName }}
    secretName: {{ .Values.manager.ingress.secretName }}
{{- end }}
{{- end }}
{{- end -}}
