{{- if and .Values.manager.enabled .Values.manager.ingress.enabled -}}
{{- if (semverCompare ">=1.19-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neuvector-webui-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
{{- if not (hasKey .Values.manager.ingress.annotations "nginx.ingress.kubernetes.io/backend-protocol") }}
{{- if .Values.manager.env.ssl }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
{{- else }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
{{- end }}
{{- end }}
{{- with .Values.manager.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
spec:
{{- if .Values.manager.ingress.ingressClassName }}
  ingressClassName: {{ .Values.manager.ingress.ingressClassName | quote }}
{{ end }}
{{- if .Values.manager.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.manager.ingress.host }}
{{- if .Values.manager.ingress.secretName }}
    secretName: {{ .Values.manager.ingress.secretName }}
{{- end }}
{{- end }}
  rules:
  - host: {{ .Values.manager.ingress.host }}
    http:
      paths:
      - path: {{ .Values.manager.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: neuvector-service-webui
            port:
              number: {{ .Values.manager.svc.mgrServerPort}}
{{- else }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: neuvector-webui-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
{{- if not (hasKey .Values.manager.ingress.annotations "nginx.ingress.kubernetes.io/backend-protocol") }}
{{- if .Values.manager.env.ssl }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
{{- else }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
{{- end }}
{{- end }}
{{- with .Values.manager.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
spec:
{{- if .Values.manager.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.manager.ingress.host }}
{{- if .Values.manager.ingress.secretName }}
    secretName: {{ .Values.manager.ingress.secretName }}
{{- end }}
{{- end }}
  rules:
  - host: {{ .Values.manager.ingress.host }}
    http:
      paths:
      - path: {{ .Values.manager.ingress.path }}
        backend:
          serviceName: neuvector-service-webui
          servicePort: {{ .Values.manager.svc.mgrServerPort}}
{{- end }}
{{- end -}}
