{{- if .Values.manager.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: neuvector-service-webui
  namespace: {{ .Release.Namespace }}
{{- with .Values.manager.svc.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    {{- with .Values.manager.svc.labels }}
    {{- toYaml . | indent 4 }}
    {{- end }}
spec:
  type: {{ .Values.manager.svc.type }}
{{- if and .Values.manager.svc.loadBalancerIP (eq .Values.manager.svc.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.manager.svc.loadBalancerIP }}
{{- end }}
  ports:
    - port: 8443
      name: manager
      protocol: TCP
{{- if .Values.manager.svc.nodePort }}
      nodePort: {{ .Values.manager.svc.nodePort }}
{{- end }}        
{{- if or (.Capabilities.KubeVersion.GitVersion | contains "-eks") (.Capabilities.KubeVersion.GitVersion | contains "-gke") }}
{{- if .Values.manager.env.ssl }}
      appProtocol: HTTPS
{{- else }}
      appProtocol: HTTP
{{- end }}
{{- end }}
  selector:
    app: neuvector-manager-pod
{{- end }}
