{{- $pre540 := false -}}                                                
{{- if regexMatch "^[0-9]+\\.[0-9]+\\.[0-9]+" .Values.tag }}               
{{- $pre540 = (semverCompare "<5.3.10-0" .Values.tag) -}}                  
{{- end }}    
{{- if .Values.cve.scanner.enabled -}}
{{- if (semverCompare ">=1.9-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: apps/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: neuvector-scanner-pod
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
spec:
  strategy:
{{ toYaml .Values.cve.scanner.strategy | indent 4 }}
  replicas: {{ .Values.cve.scanner.replicas }}
  selector:
    matchLabels:
      app: neuvector-scanner-pod
  template:
    metadata:
      labels:
        app: neuvector-scanner-pod
        {{- with .Values.cve.scanner.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.cve.scanner.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.cve.scanner.affinity }}
      affinity:
{{ toYaml .Values.cve.scanner.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.cve.scanner.tolerations }}
      tolerations:
{{ toYaml .Values.cve.scanner.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.cve.scanner.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml .Values.cve.scanner.topologySpreadConstraints | indent 8 }}
      {{- end }}
      {{- if .Values.cve.scanner.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.cve.scanner.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      {{- if .Values.cve.scanner.priorityClassName }}
      priorityClassName: {{ .Values.cve.scanner.priorityClassName }}
      {{- end }}
      {{- if .Values.leastPrivilege }}
      serviceAccountName: scanner
      serviceAccount: scanner
      {{- else }}
      serviceAccountName: {{ .Values.serviceAccount }}
      serviceAccount: {{ .Values.serviceAccount }}
      {{- end }}
      {{- if .Values.cve.scanner.runAsUser }}
      securityContext:
        runAsUser: {{ .Values.cve.scanner.runAsUser }}
      {{- end }}
      containers:
        - name: neuvector-scanner-pod
          {{- if .Values.global.azure.enabled }}
          image: "{{ .Values.global.azure.images.scanner.registry }}/{{ .Values.global.azure.images.scanner.image }}:{{ .Values.global.azure.images.scanner.tag }}"
          {{- else }}
          {{- if eq .Values.registry "registry.neuvector.com" }}
          {{- if .Values.oem }}
          image: "{{ .Values.registry }}/{{ .Values.oem }}/scanner:{{ .Values.cve.scanner.image.tag }}"
          {{- else }}
          image: "{{ .Values.registry }}/scanner:{{ .Values.cve.scanner.image.tag }}"
          {{- end }}
          {{- else }}
          {{- if .Values.cve.scanner.image.hash }}
          image: "{{ .Values.registry }}/{{ .Values.cve.scanner.image.repository }}@{{ .Values.cve.scanner.image.hash }}"
          {{- else if .Values.cve.scanner.image.registry }}
          image: "{{ .Values.cve.scanner.image.registry }}/{{ .Values.cve.scanner.image.repository }}:{{ .Values.cve.scanner.image.tag }}"
          {{- else }}
          image: "{{ .Values.registry }}/{{ .Values.cve.scanner.image.repository }}:{{ .Values.cve.scanner.image.tag }}"
          {{- end }}
          {{- end }}
          {{- end }}
          imagePullPolicy: Always
          env:
            - name: CLUSTER_JOIN_ADDR
              value: neuvector-svc-controller.{{ .Release.Namespace }}
          {{- if .Values.cve.scanner.dockerPath }}
            - name: SCANNER_DOCKER_URL
              value: {{ .Values.cve.scanner.dockerPath }}
          {{- end }}
          {{- if or .Values.internal.certmanager.enabled .Values.cve.scanner.internal.certificate.secret }}
          {{- else if (and .Values.internal.autoGenerateCert (not $pre540))}}
            - name: AUTO_INTERNAL_CERT
              value: "1"
          {{- end }}
          {{- with .Values.cve.scanner.env }}
{{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.cve.scanner.resources | indent 12 }}
          volumeMounts:
          {{- if or .Values.internal.certmanager.enabled .Values.cve.scanner.internal.certificate.secret }}
            - mountPath: /etc/neuvector/certs/internal/cert.key
              subPath: {{ .Values.cve.scanner.internal.certificate.keyFile }}
              name: internal-cert
              readOnly: true
            - mountPath: /etc/neuvector/certs/internal/cert.pem
              subPath: {{ .Values.cve.scanner.internal.certificate.pemFile }}
              name: internal-cert
              readOnly: true
            - mountPath: /etc/neuvector/certs/internal/ca.cert
              subPath: {{ .Values.cve.scanner.internal.certificate.caFile }}
              name: internal-cert
              readOnly: true
          {{- else if and .Values.internal.autoRotateCert (not $pre540) }}
            - mountPath: /etc/neuvector/certs/internal/
              name: internal-cert-dir
          {{- end }}
          {{- with .Values.cve.scanner.volumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: Always
      volumes:
      {{- if or .Values.internal.certmanager.enabled .Values.cve.scanner.internal.certificate.secret }}
        - name: internal-cert
          secret:
            secretName: {{ .Values.cve.scanner.internal.certificate.secret }}
      {{- else if and .Values.internal.autoRotateCert (not $pre540) }}
        - name: internal-cert-dir
          emptyDir:
            sizeLimit: 50Mi
      {{- end }}
      {{- with .Values.cve.scanner.volumes }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
