name: core
apiVersion: v1
version: 1.8.2
appVersion: 4.3.0
description: Helm chart for NeuVector's core services
home: https://neuvector.com
icon: https://avatars2.githubusercontent.com/u/19367275?s=200&v=4
maintainers:
  - name: becitsthere
    email: support@neuvector.com
engine: gotpl
