# Default values for neuvector.
# This is a YAML-formatted file.
# Declare variables to be passed into the templates.

exporter:
  # If false, exporter will not be installed
  enabled: false
  image:
    repository: neuvector/prometheus-exporter
    tag: latest
  # changes this to a readonly user !
  CTRL_USERNAME: admin
  CTRL_PASSWORD: admin
